### ISSUE TITLE
Module 2, week 5 peer-to-peer code review (day 2)

### ISSUE THREAD

**Issue by michaelamponsah** [raihan2bd/Leaderboard#4]
### Hi @raihan2bd , 

You have done amazing work implementing all the requirements 💯 .

**Highlights** 
- [x] Clean code ✔️ 
- [x] Project works as expected ✔️ 
- [x] Good use of ES6 syntax ✔️

**Comment by raihan2bd** [comment]
Thanks, @michaelamponsah for reviewing this Repo 👍
